import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import NavBar from "@/components/StyledComponents/Navbar";
config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Employee Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <NavBar className="navbar">
            <div className="container-fluid">
              <span className="navbar-brand mb-0 h1">Employee Manager</span>
            </div>
          </NavBar>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
